# ============================================================
# Stage 1: PlatformIO builder
# Matches the GitHub Actions build workflow exactly:
#   - ubuntu-latest base
#   - Python 3.10
#   - PlatformIO latest
#   - Builds env:esp32cam  (cd code; platformio run --environment esp32cam)
# ============================================================
# NOTE: The base image may carry CVEs that have no upstream fix yet.
# Run `docker scout cves` or `trivy image` after building to review.
# The `apt-get upgrade` below applies all available OS-level patches.
FROM python:3.12-slim AS builder

# Apply OS security patches, then install system deps needed by PlatformIO / ESP-IDF toolchain
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    git \
    curl \
    wget \
    unzip \
    zip \
    gzip \
    cmake \
    ninja-build \
    ccache \
    libusb-1.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Install PlatformIO
RUN pip install --upgrade pip && pip install --upgrade platformio

# Pre-fetch all packages: ESP32 toolchain, ESP-IDF, libraries.
# Copy only platformio.ini first so this layer is cached as long as the
# dependency manifest doesn't change — source edits won't trigger a re-download.
WORKDIR /project/code
COPY code/platformio.ini platformio.ini
RUN platformio pkg install --environment esp32cam

# Now copy the full source tree (invalidates from here on source changes).
WORKDIR /project
COPY .git/            .git/
COPY code/            code/

# Initialize git submodules (esp32-camera, esp-nn, esp-tflite-micro, stb, esp-protocols).
RUN git config --global --add safe.directory /project && \
    git submodule update --init --recursive

# Compile firmware.
WORKDIR /project/code
RUN platformio run --environment esp32cam

# ============================================================
# Stage 2: Web UI post-processor
# Mirrors the "Prepare Web UI" step from build.yaml:
#   - install markdown
#   - run generate-param-doc-tooltips.py
#   - replace $COMMIT_HASH
#   - gzip html/css/js/jpg/png/svg/map files
# ============================================================
FROM python:3.12-slim AS webui

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    gzip \
    findutils \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install markdown

WORKDIR /project
COPY .git/         .git/
COPY sd-card/      sd-card/
COPY tools/        tools/
COPY param-docs/   param-docs/

# version.txt is generated by CMake during the firmware build (written to sd-card/html/).
# Copy it from the builder stage so the Web UI reports the correct firmware version.
COPY --from=builder /project/sd-card/html/version.txt sd-card/html/version.txt

# Retrieve short commit hash (falls back to "local" when not in a git repo)
RUN git config --global --add safe.directory /project && \
    git rev-parse --short HEAD > /tmp/sha_short 2>/dev/null || echo "local" > /tmp/sha_short

RUN SHA=$(cat /tmp/sha_short) && \
    rm -rf /project/html && \
    mkdir /project/html && \
    cp -r /project/sd-card/html/* /project/html/ && \
    mkdir -p /project/html/param-tooltips && \
    cd /project/tools/parameter-tooltip-generator && python generate-param-doc-tooltips.py && \
    cd /project && cp -r /project/sd-card/html/* /project/html/ && \
    rm -f /project/html/edit_config_template.html && \
    cd /project/html && \
    find . -type f -exec sed -i "s/\$COMMIT_HASH/${SHA}/g" {} \; && \
    find . -name "*.html" -type f -exec gzip -f {} \; && \
    find . -name "*.css"  -type f -exec gzip -f {} \; && \
    find . -name "*.js"   -type f -exec gzip -f {} \; && \
    find . -name "*.jpg"  -type f -exec gzip -f {} \; && \
    find . -name "*.png"  -type f -exec gzip -f {} \; && \
    find . -name "*.svg"  -type f -exec gzip -f {} \; && \
    find . -name "*.map"  -type f -exec gzip -f {} \;

# ============================================================
# Stage 3: Artifact collector
# Assembles the same output structure that build.yaml produces
# before the pack-* jobs run:
#
#   /artifacts/
#     firmware.bin
#     bootloader.bin
#     partitions.bin
#     html/          (gzip-compressed web UI)
#     demo/
#     config/        (tflite models)
# ============================================================
FROM debian:bookworm-slim AS artifacts

# Apply OS security patches
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

COPY --from=builder \
    /project/code/.pio/build/esp32cam/firmware.bin    /artifacts/firmware.bin
COPY --from=builder \
    /project/code/.pio/build/esp32cam/bootloader.bin  /artifacts/bootloader.bin
COPY --from=builder \
    /project/code/.pio/build/esp32cam/partitions.bin  /artifacts/partitions.bin
COPY --from=webui  /project/html/                     /artifacts/html/
COPY --from=webui  /project/sd-card/demo/             /artifacts/demo/
COPY --from=webui  /project/sd-card/config/           /artifacts/config/

CMD ["sh", "-c", "echo 'Build artifacts are in /artifacts'; ls /artifacts"]
